version: "3.3"

services:
  server:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    restart: unless-stopped
    ports:
      - 7171:7171
      - 7172:7172
    volumes:
      - ../data:/otxsr/data
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SERVER_DB_HOST=mysql

  mysql:
    build:
      context: ../
      dockerfile: docker/mysql/Dockerfile
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=otserver
      - MYSQL_USER=otserver
      - MYSQL_PASSWORD=otserver
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - otserver_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  website:
    image: webdevops/php-nginx:alpine-php7
    restart: unless-stopped
    environment:
      - WEB_DOCUMENT_ROOT=/tmp/web/
      - WEB_DOCUMENT_INDEX=index.php
    ports:
      - 8080:80
    volumes:
      - ./data/web:/tmp/web
      - ../:/tmp/otserver/
    depends_on:
      mysql:
        condition: service_healthy

  login:
    image: opentibiabr/login-server:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_DBNAME=otserver
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_PASS=otserver
      - MYSQL_USER=otserver
      - ENV_LOG_LEVEL=verbose
      - LOGIN_HTTP_PORT=80
      - LOGIN_GRPC_PORT=9090
      - RATE_LIMITER_BURST=5
      - RATE_LIMITER_RATE=2
      - SERVER_NAME=OTXSERVER
      - SERVER_LOCATION=USA
      - SERVER_IP=10.2.0.227
      - SERVER_PORT=7172
#      - VOCATIONS -- map your custom vocations here, if needed, comma separated

volumes:
  otserver_data:
